### ISSUE TITLE
Cleaning data and removing duplicates

### ISSUE THREAD

**Issue by CarmenTamayo** [epiverse-trace/cleanepi#1]
I was using cleanepi() to test its functionality with some simulated data, and was trying to remove duplicated data across multiple columns. I realised that, despite specifying the range of columns across which to look for duplicates, the function would only take into account one of them (unsure of how this is decided), and would only keep the first instance of, for example, the case_id, removing all other rows as if they were duplicates, despite these rows having different contents for the other columns.

I believe it would be very useful to fix this issue so that users can use this package for this purpose, rather than having to use base R or functions from tidyverse.

Additionally, I think it would be very useful to do so in a way so that users don't have to write down the names of all the columns, or by specifying column numbers (as these might change), but take advantage of `linelist` tags, so that users can remove duplicates across these tags instead, which would save a lot of time and would be less risky. 

Something like `cleanepi(df, remove.duplicates=T, duplicates.from="tags")`

I hope this makes sense! Thank you.

**Comment by CarmenTamayo** [comment]
as an addendum to my previous issue, I think the documentation should clarify what the argument `clean.col.names` does and how to use it, right now it only says "whether to cleanup the column name or not" and it's not clear what this means
Thank you!

**Comment by Karim-Mane** [comment]
@CarmenTamayo 
This has been resolved by including the column name cleaning as part of the implicit data cleaning operations that will be performed anytime the `clean_data()` is called.
In order words, this argument is `deprecated`.
