### ISSUE TITLE
check_subject_ids() only checks for the ID length when `format` is the only provided parameter

### ISSUE THREAD

**Issue by Karim-Mane** [epiverse-trace/cleanepi#104]
``` r
readRDS(system.file("extdata", "test_df.RDS", package = "cleanepi"))
#>     study_id event_name country_code country_name date.of.admission dateOfBirth
#> 1    PS001P2      day 0            2       Gambia        01/12/2020  06/01/1972
#> 2    PS002P2      day 0            2       Gambia        28/01/2021  02/20/1952
#> 3  PS004P2-1      day 0            2       Gambia        15/02/2021  06/15/1961
#> 4    PS003P2      day 0            2       Gambia        11/02/2021  11/11/1947
#> 5    P0005P2      day 0            2       Gambia        17/02/2021  09/26/2000
#> 6    PS006P2      day 0            2       Gambia        17/02/2021         -99
#> 7    PB500P2      day 0            2       Gambia        28/02/2021  11/03/1989
#> 8    PS008P2      day 0            2       Gambia        22/02/2021  10/05/1976
#> 9    PS010P2      day 0            2       Gambia        02/03/2021  09/23/1991
#> 10   PS011P2      day 0            2       Gambia        05/03/2021  02/08/1991
#>    date_first_pcr_positive_test sex
#> 1                  Dec 01, 2020   1
#> 2                  Jan 01, 2021   1
#> 3                  Feb 11, 2021 -99
#> 4                  Feb 01, 2021   1
#> 5                  Feb 16, 2021   2
#> 6                  May 02, 2021   2
#> 7                  Feb 19, 2021   1
#> 8                  Sep 20, 2021   2
#> 9                  Feb 26, 2021   1
#> 10                 Mar 03, 2021   2
```

<sup>Created on 2024-03-14 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

``` r
cleanepi::check_subject_ids(data = readRDS(system.file("extdata", 
    "test_df.RDS", package = "cleanepi")), id_column_name = "study_id", 
    format = "PS100P2", prefix = NULL, suffix = NULL, range = NULL)
#>    study_id event_name country_code country_name date.of.admission dateOfBirth
#> 1   PS001P2      day 0            2       Gambia        01/12/2020  06/01/1972
#> 2   PS002P2      day 0            2       Gambia        28/01/2021  02/20/1952
#> 4   PS003P2      day 0            2       Gambia        11/02/2021  11/11/1947
#> 5   P0005P2      day 0            2       Gambia        17/02/2021  09/26/2000
#> 6   PS006P2      day 0            2       Gambia        17/02/2021         -99
#> 7   PB500P2      day 0            2       Gambia        28/02/2021  11/03/1989
#> 8   PS008P2      day 0            2       Gambia        22/02/2021  10/05/1976
#> 9   PS010P2      day 0            2       Gambia        02/03/2021  09/23/1991
#> 10  PS011P2      day 0            2       Gambia        05/03/2021  02/08/1991
#>    date_first_pcr_positive_test sex
#> 1                  Dec 01, 2020   1
#> 2                  Jan 01, 2021   1
#> 4                  Feb 01, 2021   1
#> 5                  Feb 16, 2021   2
#> 6                  May 02, 2021   2
#> 7                  Feb 19, 2021   1
#> 8                  Sep 20, 2021   2
#> 9                  Feb 26, 2021   1
#> 10                 Mar 03, 2021   2
```

<sup>Created on 2024-03-14 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

Only the subject ID at line 3 in the input data is detected as an outlier. The function was expected to also detect the incorrect subject IDs at line 5 and 7 of the input data.

**Comment by chartgerink** [comment]
Hi Karim - if you want my assistance on this issue (or have another need), I need a bit more context to understand how I can be of support. 

Could you please provide me with a concise and self-contained description of what you're looking for from me? Clarity on that front will be helpful for me to be of help to you.

**Comment by Karim-Mane** [comment]
@chartgerink - In the example above, the following subject ids are incorrect:
| idx  |     ids            |
|---- |------------  |
|   5  | P0005P2      |
|   7  | PB500P2      |
|   3  | PS004P2-1  |

based on the following parameters:
* a prefix that starts with `PB`
* a suffix that ends with `PS`
* a range of numbers between the prefix and the suffix comprised between `0` and `100`

When all these parameters are provided, the function is able to detect these 2 outliers.

I now want to make it work when only the `format` argument is provided i.e. in the absence of the `prefix`, `suffix` and the `range` of number between them. See below about how the function call will be:

```{r}
cleanepi::check_subject_ids(
  data           = readRDS(system.file("extdata", "test_df.RDS", package = "cleanepi")),
  id_column_name = "study_id", 
  format         = "PS100P2",
  prefix         = NULL,
  suffix         = NULL,
  range          = NULL
)
```

I want to write the part of the function that will be able to detect the incorrect ids mentioned above based on this provided format only. And this is where I need help for.

**Comment by chartgerink** [comment]
Thanks @Karim-Mane - if I understand correctly, you want the `format` argument to be automatically interpreted to infer a prefix and suffix argument. 

It looks like the current situation would be case specific for the "PSxxxPx" format - this would not be generalizable to other subject ids. Do you have documentation on the potential variability of the subject ids? It would be a shame if we invest resources to do something like this and it then appears to be not fit for purpose.

I am still not 100% on what your concrete ask is of me - it is a general request for help and I cannot say whether I am able to provide the requested support as a result. Are you asking me for a review of the structure you have in mind, for me to write the function for you, or something else? 

I am best able to prioritize my work with documented user needs - do you have any documented user needs for this feature? For what it's worth, the different components of a user need to help me prioritize are: 
- whose need is it (e.g., researcher, developer)
- how was this need identified (e.g., direct user testing, predicted need)
- what is the concrete need
- what is the resulting benefit

**Comment by chartgerink** [comment]
Thanks @Karim-Mane - that is incredibly helpful! I understand now that it is not about inferring prefix and suffixes, but about warning the user about invalid data based on `format`. 

I would recommend making the problem as small and flexible as possible. In other functions, like the date formatter, you can specify string formats: `format(date_object, "%d-%m-%Y")`. This is quite elegant but probably a bit too much for this situation.

I am not too familiar with the subject IDs, which makes me a bit hesitant to hardcode anything. If you want to warn users about invalid formatted IDs I would recommend to use regular expressions indeed. `format` could then be the regular expression that can be adjusted by the user if they want, and defaults to any common standard.

I usually create extensive test expressions using [Regex101](https://regex101.com/) with examples of both strings I know should be matched, and those that should not be matched. Subsequently, I would use [`grepl`](https://r-lang.com/grepl-in-r/) to identify the subject ids that  are and are not valid.

Note that regular expressions for R are a bit quirky - you need to add a lot of escapes, more so than in other languages.

Hope that helps 👍

**Comment by Karim-Mane** [comment]
Thanks @chartgerink 

This is very useful.

We have decided to remove the `format` argument for now from the function due to the complexity that can arise in setting it.
