### ISSUE TITLE
error when using `replace_missing_values()`

### ISSUE THREAD

**Issue by avallecam** [epiverse-trace/cleanepi#145]
from the tutorial episode on cleaning data, I get an error for column age. Do we need to specify sth in the argument to avoid this?

Here is the [cleanepi version](https://github.com/epiverse-trace/tutorials-early/blob/d0d3b0857d82a588794c79375a84a3a0299e26cb/renv/profiles/lesson-requirements/renv.lock#L506-L537) rendered in the tutorials-early, which seems to be working fine.

The version I used to generate the reprex below is the most recent available on GitHub (`"RemoteSha": "4f1e888e6ec92eaa2c234a698508233a0e35a65a"`).

cc: @Degoot-AM 

see reprex:

``` r
library(rio)
library(cleanepi)
library(dplyr)

rio::import("https://raw.githubusercontent.com/epiverse-trace/tutorials-early/main/episodes/data/simulated_ebola_2.csv") %>% 
  cleanepi::standardize_column_names() %>% 
  cleanepi::replace_missing_values()
#> Error in `dplyr::mutate()`:
#> ℹ In argument: `dplyr::across(...)`.
#> Caused by error in `across()`:
#> ! Can't compute column `age`.
#> Caused by error in `dplyr::na_if()`:
#> ! Can't recycle `y` (size 35) to size 15000.
```

<sup>Created on 2024-06-14 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by Degoot-AM** [comment]
@avallecam: Yes, you must specify the string that represents `NA`  in your data. In case you are not sure about it, just pass `na_strings =""`. It has not default values

> ```r
> library(rio)
> library(cleanepi)
> library(dplyr)
> 
> rio::import("https://raw.githubusercontent.com/epiverse-trace/tutorials-early/main/episodes/data/simulated_ebola_2.csv") %>% 
>   cleanepi::standardize_column_names() %>% 
>   cleanepi::replace_missing_values(na_strings ="")
> ```

**Comment by avallecam** [comment]
yes, this works, thanks!
