### ISSUE TITLE
Switch to base R pipe

### ISSUE THREAD

**Issue by Bisaloo** [epiverse-trace/cleanepi#147]
We're now allowed to depend on R (>=4.0.0) as per our (and the tidyverse's) policy.

It would be a good opportunity to convert the magrittr pipes to base R pipes and get rid of the downsides linked with magrittr pipes (more difficult to debug in particular).

**Comment by sbfnk** [comment]
For the base R pipe wouldn't we need to depend on >= 4.1.0?

**Comment by Bisaloo** [comment]
Oh yes, you're completely right. For some reason, I had in mind that the pipe was introduce in 4.0.0 and lambda functions in 4.1.0 but it looks that both were indeed introduced in 4.1.0 :exploding_head:
