### ISSUE TITLE
Convert to numeric bugs

### ISSUE THREAD

**Issue by Degoot-AM** [epiverse-trace/cleanepi#48]
There are some bugs in `convert_ to _numeric()` function. I listed them below
---------------------------------------------

 - [x] It only convert the first incidence of non-numeric in the target column to numeric, and coerces other non-numeric values to `NA`. see this example:
 
```r
df <- read.csv("simulated_ebola.csv")
  # Run the below command and see the results
convert_to_numeric(df, "age") 
```
 - [x] It can not run on a subset data frame. See the below example:
  ```r
 df3<-df[sample(1:150, 10),]
convert_to_numeric(df3, "age")
  ```
 This may be a result of using original index instead of actual row number in the sub data frame.

**Comment by Karim-Mane** [comment]
Thanks @Degoot-AM - This is been address in branch `fix-issue-48`.

I suggest using the argument name when uisng the function as shown below:

```{r eval = FALSE}
df3<-df[sample(1:150, 10),]
convert_to_numeric(df3,  to_numeric = "age")
```
