### ISSUE TITLE
Some bugs in `standardize_dates` and `check_date_sequence` functions

### ISSUE THREAD

**Issue by Degoot-AM** [epiverse-trace/cleanepi#49]
-[ ] `standardize_dates`: File name does not match function.
 - The file name `standardize_date`, but the function is `standardize_dates`.  The difference is only the last character `**s**` , but is a good practice to keep the same.
 - [x] The `standardize_dates`  function  does not work. Run the below the code chunk and see the error message.
 ```r
df <-read.csv("simulated_ebola.csv")
standardize_dates(df, target_columns = c("date_onset", "date_sample"))
```
- [x] The `check_date_sequence` also does not work. See the below example
 ```r
check_date_sequence(df, target_columns = c("date_onset", "date_sample"))
```
This may a result of a failure in `standardize_dates` function.

**Comment by Karim-Mane** [comment]
Thanks @Degoot-AM - This is been addressed in branch `fix-issue-49`.
