### ISSUE TITLE
`standardize_dates()` doesn't currently account for a date column with mixed formats

### ISSUE THREAD

**Issue by bahadzie** [epiverse-trace/cleanepi#54]
Given the function
```r
standardize_dates (
  data,
  target_columns  = NULL,
  format          = NULL,
  timeframe       = NULL,
  error_tolerance = 0.5
)
```
and a dataset with a column of mixed date formats e.g. 
|Date|Comment|
|-|-|
15/01/2024 | d/m/y format (UK)
02/23/2024 | m/d/y format (US)
08/02/2024 | ambiguous format
2024/01/03 | y/m/d format (ISO)

It would more accurate and useful to convert all values using unambiguously inferred date formats to an R `Date` type and only use the supplied `format` param where the date value without the format is ambiguous. 

This is an additional check to date columns and not a replacement for existing checks. 

Reporting on the percentages of each format found in date columns will be useful to end users. 

Performance might be a concern but if it is agreed that this is a good idea we can explore performant ways of including this feature in the function.

**Comment by Karim-Mane** [comment]
@bahadzie - Hndling multiple date formats is actually accounted for in Thibault's parser in the `date_guess()` function. There is a parameter in that function (`order`) that determine which format to give priority to.

I will add this argument and its documentation to the top level function (`standardise_dates()`). We can discuss this further in case it does not address your concern.
