### ISSUE TITLE
Change: `check_subject_ids` to `standardize_subject_ids`

### ISSUE THREAD

**Issue by Degoot-AM** [epiverse-trace/cleanepi#63]
To maintain consistency with the naming style of other functions in the `standardize.*` family within the package, it would be advisable to change the name from `check_subject_ids` to `standardize_subject_ids`.

**Comment by Karim-Mane** [comment]
@Degoot-AM - Thanks for raising this up.

The function in essence does not make any changes to the values in the subject IDs column. It only checks if all subject IDs are complying with the expected format and remove those that do not.

I suggest that we leave it as it is currently and update the current framework to: 

* make sure the `check_subject_ids()` function to detect the wrong IDs and report them. This mean that the `remove` argument should be set to `FALSE` by default. When it is set to `TRUE`, the incorrect IDs are removed and reported.
* create a `standardize_ids()` function that allows the user to provide the correct values for the incorrect subject IDs.
