### ISSUE TITLE
Some old commits are still appearing in every PR. 

### ISSUE THREAD

**Issue by Karim-Mane** [epiverse-trace/cleanepi#70]
Up to 20 commits are always caried onto any new branch

This might be the reason why I cannot rebase and merge and also the reason for render readme fails

**Comment by jamesmbaazam** [comment]
Hi @Karim-Mane, I'm unable to reproduce this. I'm wondering if it is an issue with your global git configuration. Could you post your git config here? 

Be sure to remove the ones that begin with `user.` and `branch.`

**Comment by Karim-Mane** [comment]
@jamesmbaazam - thanks for looking into this.

Seems like the issue is only happening the the PRs that I raised given that you and others do not have this issue.

I have deleted the cleanepi folder on my machine and recloned the repo.

The issue is no longer happening (see PR opened to fix issue #73)
