### ISSUE TITLE
Reference to figure in the design vignette

### ISSUE THREAD

**Issue by Degoot-AM** [epiverse-trace/cleanepi#77]
Add help text (alt-text) and correct the reference of the main figure in the design vignette

**Comment by Karim-Mane** [comment]
I have removed the reference to this figure and replaced it with something like `the figure above` as we only have 1 figure in the design document.

I have also updated the design vignette to account for the recent changes.

**Comment by Degoot-AM** [comment]
This issue has been addressed by PR #120
