### ISSUE TITLE
Importing numberize package

### ISSUE THREAD

**Issue by Degoot-AM** [epiverse-trace/cleanepi#89]
Also note that since {numberize} is not on CRAN, you may have to find a way not to Import it unless it'll go on CRAN. 

_Originally posted by @jamesmbaazam in https://github.com/epiverse-trace/cleanepi/pull/86#pullrequestreview-1908523898_

**Comment by Karim-Mane** [comment]
{numberize} will go on CRAN and @bahadzie has done all the necessary work to get it submitted ASAP.

But I will use this issue to recall {numberize} to convert a vector of character into numeric.
