### ISSUE TITLE
cleanepi position in the data pipeline

### ISSUE THREAD

**Issue by Bisaloo** [epiverse-trace/cleanepi#9]
I would like to open the discussion on the exact position of cleanepi in the data pipeline as this has important implications in the entire suite of packages from the "early tasks" in the epi pipeline. Once this discussion has ended, it would be great to summarize the outcome in a dedicated "Design" vignette.

- Is cleanepi going to be specific for linelist data, count data, or any generic data.frame? If the latter, it becomes more difficult to justify it compared to general data cleaning packages such as janitor.
- Do you envision that cleanepi is used before or after converting the object to a linelist/incidence object? In other words, does the pipeline go:
  `readepi -> linelist -> cleanepi`
  or:
  `readepi -> cleanepi -> linelist`
  This has implications on cleanepi design (among other things, use of object-oriented design), but also could help decide whether readepi should return a linelist object, and will inform future development of linelist

**Comment by Bisaloo** [comment]
My personal preference would be for cleanepi to work specifically with linelist data. This would make its position in the global R package ecosystem much easier to define in comparison to generic data cleaning packages and would push us to directly output linelist objects in readepi, which goes in the general direction we are going for to get tightly integrated pipelines.

**Comment by Bisaloo** [comment]
After an in-person discussion with @bbah74 @Karim-Mane @bahadzie, one third option we mentioned was for cleanepi to work both with linelist and classic datasets through [S3 dispatch](https://adv-r.hadley.nz/s3.html#s3-methods).

It would have the benefit of tightly integrating with the rest of our ecosystem without constraining the users too much into our tools.

**Comment by Degoot-AM** [comment]
I have add the summary of this discussion into the design vignette and raised PR #62.
